export const PUSH_INFO = 'push_info' //添加todo
export const SHOW_SEARCH = 'show_search'
export const PUSH_WORK = 'push_work'
export const PUSH_CHANGE_CLASS = 'push_change_class'
export const DETAUL_LIST = 'detail_list'
export const GET_CLASSMATES = 'get_classmates'
export const GET_NEW_CLASS = 'get_new_class'
export const PUSH_NEWCLASS = 'push_newclass'
export const CLEARFILE = 'clearfile'